### ISSUE TITLE
Add a shortcut during solving: "H" or "?" to print all keyboard shortcuts

### ISSUE THREAD

**Issue by icyflame** [icyflame/node-cube-cli-timer#46]

**Comment by Saurabh3333** [comment]
Do keyboard shortcuts same as the things showing during `solve --help`? What should be the colour scheme for showing the keyboard shortcuts?

**Comment by icyflame** [comment]
No, `solve --help` is the overall module shortcuts. When you run `solve`, you will see shortcuts on the top right part of your screen. Those shortcuts should be displayed when user presses `H` or `?`

**Comment by Saurabh3333** [comment]
Do keypress module support `'?'`? I am getting an error. On pressing `'?'` it is responding with an undefined value.

**Comment by icyflame** [comment]
@Saurabh3333 Ah, okay. Then just stick to "H" for now

**Comment by icyflame** [comment]
Fixed in #47
